export interface Product{
  id:number,
  codigo:string,
  nome:string,
  nomeCientifico:string,
  outrosNomes:string,
  descricao:string,
  img:any,
  valor:number,
  thumb:any
  quantidade_estoque:number
  quantidade:number;
  valorFrete:number;
  cozer:string,
  folha:boolean,
  raiz:boolean,
  fruto:boolean,
  flor:boolean,
  semente:boolean
}
